### ISSUE TITLE
Update to brunch 1.x

### ISSUE THREAD

**Issue by paulmillr** [charlesjolley/ember-brunch#1]
Hi. Could you please update the project to brunch 1.x (as I see, it's currently for 1.0-β)?

I want to put your stuff on brunch front page, looks pretty interesting.

**Comment by charlesjolley** [comment]
Hi Paul,  

Unfortunately the changes in brunch 1.x are not compatible with this because they don't support 'generic' plugins anymore (afaict). I used a generic plugin to create the HTML5 manifest. Does that make sense? Is that still possible? If so I could try to update it.

-C

**Comment by paulmillr** [comment]
this is correct, it's not possible in 1.x. but your idea about manifest is great, I'll think of something by the nearest release.

**Comment by charlesjolley** [comment]
That would be great! Tx.
